services:
  fe:
    build: ./fe
    working_dir: /app/fe
    env_file:
      - ./fe/.env
    ports:
      - "3000:3000"
  be:
    build: ./be
    working_dir: /app/be
    env_file:
      - ./be/.env
    ports: 
      - "8080:8080"
